camera:
  IP: localhost
  USERNAME: root_nesic
  PASSWORD: Nesic123_
  PORT: 11100

profiles:
  HD:
    width: 1280
    height: 720
    bitrateLimit: 1536
  FullHD:
    width: 1920
    height: 1080
    bitrateLimit: 4196

currentProfile: FullHD